namespace DB
{
	public enum CharlistSymboleID
	{
		SymboleChar_TYUUTEN = 0,
		SymboleChar_COLON = 1,
		SymboleChar_SEMICOLON = 2,
		SymboleChar_QUESTION = 3,
		SymboleChar_EXCLAMATION = 4,
		SymboleChar_TILDE = 5,
		SymboleChar_SLASH = 6,
		SymboleChar_PLUS = 7,
		SymboleChar_MINUS = 8,
		SymboleChar_KAKERU = 9,
		SymboleChar_WARU = 10,
		SymboleChar_EQUAL = 11,
		SymboleChar_OSU = 12,
		SymboleChar_MESU = 13,
		SymboleChar_SUBETE = 14,
		SymboleChar_SHARP = 15,
		SymboleChar_AMPERSAND = 16,
		SymboleChar_ASTERISK = 17,
		SymboleChar_AT = 18,
		SymboleChar_STAR = 19,
		SymboleChar_MARU = 20,
		SymboleChar_2MARU = 21,
		SymboleChar_KUKEI = 22,
		SymboleChar_SQUARE = 23,
		SymboleChar_TRIANGLE = 24,
		SymboleChar_TRIANGLE2 = 25,
		SymboleChar_ONNPU = 26,
		SymboleChar_DAGGER = 27,
		SymboleChar_D_DAGGER = 28,
		SymboleChar_SIGMA = 29,
		SymboleChar_ALPHA = 30,
		SymboleChar_BETA = 31,
		SymboleChar_GAMMA = 32,
		SymboleChar_THETA = 33,
		SymboleChar_PHI = 34,
		SymboleChar_PSI = 35,
		SymboleChar_OMEGA = 36,
		SymboleChar_DE = 37,
		SymboleChar_YO = 38,
		SymboleChar_DOLLAR = 39,
		SymboleChar_LEFT_PARENTHESIS = 40,
		SymboleChar_RIGHT_PARENTHESIS = 41,
		SymboleChar_PERIOD = 42,
		SymboleChar_LOW_LINE = 43,
		SymboleChar_Space = 44,
		SumboleChar_End = 45,
		Begin = 0,
		End = 46,
		Invalid = -1
	}
}
