using System;

namespace Manager.MaiStudio
{
	[Serializable]
	public enum ReleaseConditionTotalKind
	{
		None,
		MAI2DX_N_PLAY,
		MUSIC,
		DIFFICULTY,
		TODOHUKEN,
		TENPO,
		MUSIC_GROUP,
		N_PLAY,
		CHARA_KANYU,
		CHARA_KAISU,
		CHARA_KAKUSEI,
		MAP_CHARA_SIYOU,
		MAP_CHARA_KAKUSEI,
		MAP_KAIKIN,
		MAP_COMPLETE,
		NPC_OTOMODACHI_N_WIN,
		NPC_OTOMODACHI_N_REN_WIN,
		ZENKOKU_OTOMODACHI_N_WIN,
		ZENKOKU_OTOMODACHI_N_REN_WIN,
		MAP_KYORI,
		LOGIN_RENZOKU,
		LOGIN_RUIKEI,
		TODOHUKEN_SEIHA
	}
}
