using System;

namespace Manager.MaiStudio
{
	[Serializable]
	public enum ReleaseItemConditionKind
	{
		None,
		PLAY_KIKAN,
		CHARA_KANYUU,
		CHARA_SIYOU,
		CHARA_KAKUSEI,
		MAP_CHARA_RUIKEI_KAISUU,
		MAP_CHARA_RUIKEI_KAKUSEI,
		MAP_KAIKIN,
		MAP_COMPLETE,
		MUSIC_PLAY,
		MUSIC_TASSEI,
		MUSIC_ONCE_PLAY,
		LOGIN_RENZOKU_DAYS,
		LOGIN_RUIKEI_DAYS,
		PLAY_GAME_COUNT,
		PLAY_MUSIC_COUNT,
		CHUNITHM_GAME_MUSIC_COUNT,
		ONEGKI_GAME_MUSIC_COUNT,
		NPC_WIN_LOSE,
		NPC_REN_WIN_LOSE,
		PC_WIN_LOSE,
		PC_REN_WIN_LOSE,
		RATING
	}
}
